# For development
version: '3.8'

services:
  auth.ui: 
    build:
      context: "./packages/auth.ui"
      dockerfile: "../../docker/Dockerfile.dev"
    image: eldekyfin/node-dev
    env_file: .env
    volumes:
      - ./packages/auth.ui:/var/app:delegated
      - /var/app/node_modules
    depends_on:
      - auth.api
    ports:
      - 5051:5051

  auth.api:
    build:
      context: .
      dockerfile: "docker/Dockerfile.dev"
    image: eldekyfin/node-dev
    env_file: .env
    volumes:
      - ./packages/auth.api/:/var/app
      - /var/app/node_modules  # Mount node_modules from the container itself
    # depends_on:
    #   - redis
    ports:
      - 5052:5052
    depends_on:
      - rabbit


  db:
    image: yobasystems/alpine-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - "./data/db.dev:/var/lib/mysql"

  # redis:
  #   image: redis:6-alpine
  #   command: redis-server --save 60 1 --loglevel warning
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq
    # ports:
    #   - "5672:5672"  # AMQP protocol port
    #   - "15672:15672"  # Management UI
    env_file: .env


  myinfo.ui: 
    build:
      context: "./packages/auth.ui"
      dockerfile: "../../docker/Dockerfile.dev"
    image: eldekyfin/node-dev
    env_file: .env
    volumes:
      - ./packages/myinfo.ui:/var/app:delegated
      - /var/app/node_modules
    depends_on:
      - myinfo.api
    ports:
      - 5050:5050

  myinfo.api:
    build:
      context: "./packages/myinfo.api"
      dockerfile: "../../docker/Dockerfile.dev"
    image: eldekyfin/node-dev
    env_file: .env
    volumes:
      - ./packages/myinfo.api:/var/app:delegated
      - /var/app/node_modules
    ports:
      - 5053:5053
    depends_on:
      - rabbit

  myinfo.scanner:
    build:
      context: "./packages/myinfo.scanner"
      dockerfile: "../../docker/Dockerfile.dev"
    image: eldekyfin/node-dev
    env_file: .env
    volumes:
      - ./packages/myinfo.scanner:/var/app:delegated
      - /var/app/node_modules
    depends_on:
      - rabbit

