# For development
version: '3.8'

services:
  auth.ui: 
    build:
      context: "./packages/auth.ui"
      dockerfile: "../../docker/Dockerfile.dev"
    image: eldekyfin/node-dev
    env_file: .env
    volumes:
      - ./packages/auth.ui:/var/app:delegated
      - ./node_modules:/var/app/node_modules
      - /var/app/node_modules/shared
    depends_on:
      - auth.api
    ports:
      - 5051:5050

  auth.api:
    build:
      context: .
      dockerfile: "docker/Dockerfile.dev"
    image: eldekyfin/node-dev
    env_file: .env
    volumes:
      - ./packages/auth.api/:/var/app 
      - ./node_modules:/var/app/node_modules
      - /var/app/node_modules/shared  # Mount node_modules from the container itself
    # depends_on:
    #   - redis
    ports:
      - 5052:5050
    depends_on:
      - db
      - rabbit


  db:
    image: yobasystems/alpine-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - "./data/db.dev:/var/lib/mysql"

  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    # ports:
    #   - "5672:5672"  # AMQP protocol port
    #   - "15672:15672"  # Management UI
    env_file: .env


  myinfo.ui: 
    build:
      context: "./packages/auth.ui"
      dockerfile: "../../docker/Dockerfile.dev"
    image: eldekyfin/node-dev
    env_file: .env
    volumes:
      - ./packages/myinfo.ui:/var/app:delegated
      - ./node_modules:/var/app/node_modules
      - /var/app/node_modules/shared
    depends_on:
      - myinfo.api
    ports:
      - 5050:5050

  myinfo.api:
    build:
      context: "./packages/myinfo.api"
      dockerfile: "../../docker/Dockerfile.dev"
    image: eldekyfin/node-dev
    env_file: .env
    volumes:
      - ./packages/myinfo.api:/var/app:delegated
      - ./node_modules:/var/app/node_modules
      - /var/app/node_modules/shared
    ports:
      - 5053:5050
    depends_on:
      - db
      - rabbit

  myinfo.scanner:
    build:
      context: "./packages/myinfo.scanner"
      dockerfile: "../../docker/Dockerfile.dev"
    image: eldekyfin/node-dev
    env_file: .env
    volumes:
      - ./packages/myinfo.scanner:/var/app:delegated
      - ./node_modules:/var/app/node_modules
      - /var/app/node_modules/shared
    depends_on:
      - rabbit

