apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
spec:
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      automountServiceAccountToken: false
      containers:
        - name: auth-api
          image: eldekyfin/auth.api
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: app-config
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 5050

---
apiVersion: v1
kind: Service
metadata:
  name: auth-api
spec:
  type: NodePort
  selector:
    app: auth-api
  ports:
    - port: 5050
      targetPort: 5050
      nodePort: 30002
