apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-ui
spec:
  selector:
    matchLabels:
      app: auth-ui
  template:
    metadata:
      labels:
        app: auth-ui
    spec:
      automountServiceAccountToken: false
      containers:
        - name: auth-ui
          image: eldekyfin/auth.ui
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: app-config
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5050

---
apiVersion: v1
kind: Service
metadata:
  name: auth-ui
spec:
  type: NodePort
  selector:
    app: auth-ui
  ports:
    - port: 5050
      targetPort: 5050
      nodePort: 30001
