apiVersion: apps/v1
kind: Deployment
metadata:
  name: myinfo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myinfo-db
  template:
    metadata:
      labels:
        app: myinfo-db
    spec:
      automountServiceAccountToken: false
      containers:
        - name: myinfo-db
          image: yobasystems/alpine-mariadb
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYINFO_DB_NAME
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYINFO_DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYINFO_DB_PASS
          volumeMounts:
            - name: myinfo-db-data
              mountPath: /var/lib/mysql
      volumes:
        - name: myinfo-db-data
          hostPath:
            path: /k8s/myinfo
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: myinfo-db
spec:
  type: ClusterIP
  selector:
    app: myinfo-db
  ports:
    - port: 3306
      targetPort: 3306
