apiVersion: apps/v1
kind: Deployment
metadata:
  name: myinfo-api
spec:
  selector:
    matchLabels:
      app: myinfo-api
  template:
    metadata:
      labels:
        app: myinfo-api
    spec:
      automountServiceAccountToken: false
      containers:
        - name: myinfo-api
          image: eldekyfin/myinfo.api
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: app-config
          resources:
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 5050

---
apiVersion: v1
kind: Service
metadata:
  name: myinfo-api
spec:
  type: NodePort
  selector:
    app: myinfo-api
  ports:
    - port: 5050
      targetPort: 5050
      nodePort: 30003
