apiVersion: apps/v1
kind: Deployment
metadata:
  name: recon-auth
spec:
  selector:
    matchLabels:
      app: recon-auth
  template:
    metadata:
      labels:
        app: recon-auth
    spec:
      automountServiceAccountToken: false
      containers:
        - name: recon-auth
          image: eldekyfin/recon.auth
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: recon-config
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5001

---
apiVersion: v1
kind: Service
metadata:
  name: recon-auth
spec:
  type: NodePort
  selector:
    app: recon-auth
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 30001
