apiVersion: apps/v1
kind: Deployment
metadata:
  name: recon-chidori
spec:
  selector:
    matchLabels:
      app: recon-chidori
  template:
    metadata:
      labels:
        app: recon-chidori
    spec:
      automountServiceAccountToken: false
      containers:
        - name: recon-chidori
          image: eldekyfin/recon.chidori
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: recon-config

          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5050

---
apiVersion: v1
kind: Service
metadata:
  name: recon-chidori
spec:
  type: NodePort
  selector:
    app: recon-chidori
  ports:
    - port: 5050
      targetPort: 5050
      nodePort: 30000
