FROM node:lts-slim
ARG APP

# Build shared package
WORKDIR /var/shared

COPY packages/shared .
RUN yarn install; yarn build

# App build
WORKDIR /var/app
COPY packages/${APP}/package.json ./
RUN yarn install

# Copy data
COPY packages/${APP} .
RUN yarn build

CMD [ "yarn", "start" ]