FROM node:lts-slim
ARG APP
WORKDIR /var/app/

COPY packages/shared/package.json ../shared/
RUN cd ../shared; yarn install

COPY packages/${APP}/package.json ./
RUN yarn install

COPY packages/${APP} .
COPY packages/shared ../shared

RUN cd ../shared; yarn build;
RUN yarn build;

CMD [ "yarn", "start" ]