FROM node:lts-slim
WORKDIR /var/app

COPY packages/auth.api/package.json ./
RUN yarn install

COPY packages/shared node_modules/shared
COPY packages/auth.api . 

RUN yarn build; \
    rm -rf src

EXPOSE 5052
CMD [ "yarn", "start" ]