FROM node:lts-slim
WORKDIR /var/app
ARG APP

COPY packages/${APP}/package.json ./
RUN yarn install

COPY packages/shared node_modules/shared
COPY packages/shared shared
COPY packages/${APP} . 

RUN yarn build; \
    rm -rf src

CMD [ "yarn", "start" ]